//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phim
    {
        public int idPhim { get; set; }
        public string Ten { get; set; }
        public string GioiThieu { get; set; }
        public string Url { get; set; }
        public string NguoiDang { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> NgayChieu { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public int idTL { get; set; }
        public int idQG { get; set; }
    
        public virtual quocgia quocgia { get; set; }
        public virtual theloai theloai { get; set; }
    }
}
