//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class theloai
    {
        public theloai()
        {
            this.phims = new HashSet<phim>();
        }
    
        public int idTL { get; set; }
        public string TenTL { get; set; }
    
        public virtual ICollection<phim> phims { get; set; }
    }
}
